### PR TITLE
Hostname fix

### LINKED ISSUE #49: Permission denied while changing hostname
`exit status 1 bash: /etc/hostname: Permission denied`

getting this error after vm gets created and connection is estabilished but while executing this command

_fmt.Sprintf("sudo sh -c 'echo %s > /etc/hostname'", newHostname)_

@mhewedy does this error sound familiar to you? I'm stuck with this now, will look into this when I get some time

### PR DESCRIPTION
**Pull request by akhiljns**
closes #49 

@mhewedy ignore the healthcheck changes while reviewing the PR, i have cut the branch from the healthcheck PR those changes would go once the healthcheck PR gets merged

### CODE REVIEW

File: images/cached.go [hunk 1]
```diff
@@ -2,19 +2,20 @@ package images
...
+	"github.com/mhewedy/vermin/progress"
 )
 
 const ova = ".ova"
 
 func Remove(imageName string) error {
 	existingImgs, _ := List()
 	if !contains(existingImgs, imageName) {
-		return errors.New("Image not found")
+		return errors.New("image not found")
```
Comment (akhiljns) [inline images/cached.go:18]: @mhewedy these are lint warnings thrown by go lint and reviewdog

**Review by mhewedy — APPROVED** [review]
