### PR TITLE
get ip address of running vm

### LINKED ISSUE #10: Cannot  Establishing connection
Hi there,

created the file and ran it:

sudo apt update -y
sudo apt install redis-server -y
sudo sed -i 's/^supervised no/supervised systemd/' /etc/redis/redis.conf
sudo systemctl restart redis.service
sudo systemctl status redis

vermin create ubuntu/focal script.sh

the machine was created, I can see it.
but cannot establish a connection using:
 vermin ssh vm_01
windows10, vbox 6.1

Thanks!

### LINKED ISSUE #46: After creating the vm estabilishing the connection fails
the vm has been created and i can see it running but on performing ssh into the VM it throws following logs

```
yscall.GetFileAttributesEx(0xc008d5e840?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc0054258e8 sp=0xc005425898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008d5e840, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc005425c38 sp=0xc0054258e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008d5e840, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc005425c70 sp=0xc005425c38 pc=0x77c4dd
os/exec.chkStat({0xc008d5e840?, 0xc002b13040?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc005425c90 sp=0xc005425c70 pc=0x990f98
os/exec.findExecutable({0xc002b13040, 0x25}, {0xc004480b00, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc005425ce8 sp=0xc005425c90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc005425e58 sp=0xc005425ce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc007645da0, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc005425ee8 sp=0xc005425e58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc005425f90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc005425f58 sp=0xc005425ee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc005425fc8 sp=0xc005425f58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc005425fe0 sp=0xc005425fc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc005425fe8 sp=0xc005425fe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98

goroutine 6700 [runnable, locked to thread]:
runtime.cgocall(0x6fc4e0, 0xc0077b7ac8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc00542f7d8 sp=0xc00542f7a0 pc=0x69817e
syscall.SyscallN(0x7ffee9600650?, {0xc00542f870?, 0x3?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc00542f850 sp=0xc00542f7d8 pc=0x6f7aa7
syscall.Syscall(0x29?, 0xc008f3d9e0?, 0xffffffffffffffff?, 0xc00542f8d8?, 0x6a0aa5?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc00542f898 sp=0xc00542f850 pc=0x6f77f5
syscall.GetFileAttributesEx(0xc008fc01e0?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc00542f8e8 sp=0xc00542f898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008fc01e0, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc00542fc38 sp=0xc00542f8e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008fc01e0, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc00542fc70 sp=0xc00542fc38 pc=0x77c4dd
os/exec.chkStat({0xc008fc01e0?, 0xc0041f3d80?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc00542fc90 sp=0xc00542fc70 pc=0x990f98
os/exec.findExecutable({0xc0041f3d80, 0x25}, {0xc003ec5c00, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc00542fce8 sp=0xc00542fc90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc00542fe58 sp=0xc00542fce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc007f9b8c0, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc00542fee8 sp=0xc00542fe58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc00542ff90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc00542ff58 sp=0xc00542fee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc00542ffc8 sp=0xc00542ff58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc00542ffe0 sp=0xc00542ffc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00542ffe8 sp=0xc00542ffe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98

goroutine 6701 [runnable, locked to thread]:
runtime.cgocall(0x6fc4e0, 0xc0077cc2c8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc0054217d8 sp=0xc0054217a0 pc=0x69817e
syscall.SyscallN(0x7ffee9600650?, {0xc005421870?, 0x3?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc005421850 sp=0xc0054217d8 pc=0x6f7aa7
syscall.Syscall(0x29?, 0xc008f3daa0?, 0xffffffffffffffff?, 0xc0054218d8?, 0x6a0aa5?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc005421898 sp=0xc005421850 pc=0x6f77f5
syscall.GetFileAttributesEx(0xc008fc0240?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc0054218e8 sp=0xc005421898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008fc0240, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc005421c38 sp=0xc0054218e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008fc0240, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc005421c70 sp=0xc005421c38 pc=0x77c4dd
os/exec.chkStat({0xc008fc0240?, 0xc000cf4ac0?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc005421c90 sp=0xc005421c70 pc=0x990f98
os/exec.findExecutable({0xc000cf4ac0, 0x25}, {0xc00235e400, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc005421ce8 sp=0xc005421c90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc005421e58 sp=0xc005421ce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc007f9b920, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc005421ee8 sp=0xc005421e58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc005421f90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc005421f58 sp=0xc005421ee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc005421fc8 sp=0xc005421f58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc005421fe0 sp=0xc005421fc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc005421fe8 sp=0xc005421fe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98

goroutine 6702 [runnable, locked to thread]:
runtime.cgocall(0x6fc4e0, 0xc0044646c8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc00542b7d8 sp=0xc00542b7a0 pc=0x69817e
syscall.SyscallN(0x7ffee9600650?, {0xc00542b870?, 0x3?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc00542b850 sp=0xc00542b7d8 pc=0x6f7aa7
syscall.Syscall(0x29?, 0xc008e43740?, 0xffffffffffffffff?, 0xc00542b8d8?, 0x6a0aa5?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x35 fp=0xc00542b898 sp=0xc00542b850 pc=0x6f77f5
syscall.GetFileAttributesEx(0xc008cd8b70?, 0x0, 0x0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:750 +0x65 fp=0xc00542b8e8 sp=0xc00542b898 pc=0x74be65
os.stat({0xac790a, 0x4}, {0xc008cd8b70, 0x29}, 0x1)
        C:/Program Files/Go/src/os/stat_windows.go:35 +0x289 fp=0xc00542bc38 sp=0xc00542b8e8 pc=0x77c849
os.statNolog(...)
        C:/Program Files/Go/src/os/stat_windows.go:121
os.Stat({0xc008cd8b70, 0x29})
        C:/Program Files/Go/src/os/stat.go:13 +0x3d fp=0xc00542bc70 sp=0xc00542bc38 pc=0x77c4dd
os/exec.chkStat({0xc008cd8b70?, 0xc003ff6740?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:20 +0x18 fp=0xc00542bc90 sp=0xc00542bc70 pc=0x990f98
os/exec.findExecutable({0xc003ff6740, 0x25}, {0xc004120f00, 0xb, 0xa44120?})
        C:/Program Files/Go/src/os/exec/lp_windows.go:48 +0xd6 fp=0xc00542bce8 sp=0xc00542bc90 pc=0x991176
os/exec.LookPath({0xac9a96, 0xa})
        C:/Program Files/Go/src/os/exec/lp_windows.go:115 +0x49c fp=0xc00542be58 sp=0xc00542bce8 pc=0x99169c
os/exec.Command({0xac9a96, 0xa}, {0xc000d88720, 0x6, 0xa44120?})
        C:/Program Files/Go/src/os/exec/exec.go:419 +0x217 fp=0xc00542bee8 sp=0xc00542be58 pc=0x98c7b7
github.com/mhewedy/vermin/cmd.(*Cmd).Run(0xc00542bf90)
        D:/programs/vermin/cmd/cmd.go:93 +0x170 fp=0xc00542bf58 sp=0xc00542bee8 pc=0x992dd0
github.com/mhewedy/vermin/ip.ping.func1(0x0?)
        D:/programs/vermin/ip/ping.go:26 +0x114 fp=0xc00542bfc8 sp=0xc00542bf58 pc=0x998fd4
github.com/mhewedy/vermin/ip.ping.func2()
        D:/programs/vermin/ip/ping.go:28 +0x27 fp=0xc00542bfe0 sp=0xc00542bfc8 pc=0x998e87
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00542bfe8 sp=0xc00542bfe0 pc=0x6fad21
created by github.com/mhewedy/vermin/ip.ping in goroutine 1
        D:/programs/vermin/ip/ping.go:25 +0x98
    .............
```

PS : _this is just a part of infinite logs that i keeps generating_

### PR DESCRIPTION
**Pull request by akhiljns**
now instead of searching for ip address in subnet it will get actual ip of running vm

closes #46 
closes #10

### CODE REVIEW

File: hypervisor/base/types.go [hunk 1]
```diff
@@ -22,6 +22,8 @@ type Hypervisor interface {
 
 	Modify(vmName string, cpus int, mem int) error
 
+	GetVMProperty(vmName, property string) (*string, error)
```
Comment (akhiljns) [inline hypervisor/base/types.go:25]: added this in hypervisor assuming we will be doing this with qemu as well to search for ip address

File: hypervisor/virtualbox/virtualbox.go [hunk 2]
```diff
@@ -114,6 +129,29 @@ func (*virtualbox) Modify(vmName string, cpus int, mem int) error {
 	return nil
 }
 
+func (*virtualbox) GetVMProperty(vmName, property string) (*string, error) {
```
Comment (mhewedy) [inline hypervisor/virtualbox/virtualbox.go:132]: so this method depends on 
https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/guestadd-guestprops.html

LGTM. hopefully this works for bridge network

**Review by mhewedy — APPROVED** [review]

File: hypervisor/virtualbox/virtualbox.go (hunk 2 above)
Comment (akhiljns) [reply hypervisor/virtualbox/virtualbox.go:132]: yep, this works for bridge network, also i need to test this on a linux/unix machine so dont merge this yet, I have marked this as draft PR, will update once i test it on unix

Comment (akhiljns) [reply hypervisor/virtualbox/virtualbox.go:132]: this does not work with unix/linux systems

apparantly the guestProperty get command only works for windows machines on powershell (i tried it in git bash and it failed there as well) for linux/unix systems we have to use guestProperty enumerate and then parse that object and grep ip address field from the string

updating this PR with new code

File: hypervisor/virtualbox/virtualbox.go [hunk 3]
```diff
@@ -114,6 +129,38 @@ func (*virtualbox) Modify(vmName string, cpus int, mem int) error {
...
+
+	guestProperty, err := vboxManage("guestproperty",
+		"enumerate",
+		vmName).Call()
+
+	if err != nil {
+		return nil, err
+	}
+
+	time.Sleep(30 * time.Second)
```
Comment (akhiljns) [inline hypervisor/virtualbox/virtualbox.go:146]: putting sleep as this get property works only when the vm is up and running, this wait time is to ensure it is up, will change this to health check based approach instead of sleep

Comment (mhewedy) [reply hypervisor/virtualbox/virtualbox.go:146]: You can open an issue and send PR later if you like

File: hypervisor/virtualbox/virtualbox.go (hunk 2 above)
Comment (mhewedy) [reply hypervisor/virtualbox/virtualbox.go:132]: So enumerate works for both Windows and Linux?

Comment (akhiljns) [reply hypervisor/virtualbox/virtualbox.go:132]: yes enumerate works for both tested this on all platform mac windows and linux

File: hypervisor/virtualbox/virtualbox.go (hunk 3 above)
Comment (mhewedy) [reply hypervisor/virtualbox/virtualbox.go:146]: BTW, the health check solution needs to have some retry mechanism (similar to the one in k8s or so)

**Review by mhewedy — APPROVED** [review]

File: hypervisor/virtualbox/virtualbox.go (hunk 3 above)
Comment (akhiljns) [reply hypervisor/virtualbox/virtualbox.go:146]: yep i just found out that the enumerate command also returns the state of the vm i'm going to put a loop on that untill it shows up and then connect
