### PR TITLE
Ipfind fix

### LINKED ISSUE #54: Error while provisioning Vm getting EOF
Screenshot 2024-04-08 214252

@mhewedy getting this error when it reaches provisioning 

trying this in windows 11

### PR DESCRIPTION
**Pull request by akhiljns**
replacing all ip.Find with ip.Get to avoid unnecessary goroutine spawn

@mhewedy could you merge other PRs before this so that other changes does not reflect in this one
closes #54

### CODE REVIEW

File: images/utils.go [hunk 1]
```diff
@@ -16,7 +16,7 @@ func contains(a []string, s string) bool {
 
 func validateName(imageName string) error {
 	if len(strings.Split(imageName, "/")) != 2 {
-		return errors.New("Name doesn't follow pattern <user>/<box>")
+		return errors.New("name doesn't follow pattern <user>/<box>")
```
Comment (akhiljns) [inline images/utils.go:19]: these are lint warnings

**Review by mhewedy — APPROVED** [review]

**Comment by akhiljns** [comment]
@mhewedy you could add git hooks so that anyone with merge access can only merge into master after there is atleast 1 approval and all checks have been passed

this can be configured from the repository settings

**Comment by mhewedy** [comment]
> @mhewedy you could add git hooks so that anyone with merge access can only merge into master after there is atleast 1 approval and all checks have been passed
> 
> this can be configured from the repository settings

I've configured it from the settings.
